export const LOAD_USERS_START = "LOAD_USERS_START";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_ERORR = "LOAD_USERS_ERORR";

export const LOAD_USERS_START2 = "LOAD_USERS_START2";
export const LOAD_USERS_SUCCESS2 = "LOAD_USERS_SUCCESS2";
export const LOAD_USERS_ERORR2 = "LOAD_USERS_ERORR2";

export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";

export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATEUSER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

export const SHOW_USER_START = "SHOW_USER_START";
export const SHOW_USER_SUCCESS = "SHOW_USER_SUCCESS";
export const SHOW_USER_ERROR = "SHOW_USER_ERROR";
export const SHOW_USER_RES_CLEAN = "SHOW_USER_RES_CLEAN";

export const CART_ADDTO_CART_START = "CART_ADDTO_CART_START";
export const CART_ADDTO_CART_SUCCESS = "CART_ADDTO_CART_SUCCESS";
export const CART_ADDTO_CART_ERROR = "CART_ADDTO_CART_ERROR";

export const ADDTO_CART_START = "ADDTO_CART_START";
export const ADDTO_CART_SUCCESS = "ADDTO_CART_SUCCESS";
export const ADDTO_CART_ERROR = "ADDTO_CART_ERROR";
